"""Initial migration

Revision ID: 5c2c93ae6ddb
Revises:
Create Date: 2026-01-18 18:17:26.601597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2c93ae6ddb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=True),
    sa.Column('faculty_id', sa.String(length=255), nullable=True),
    sa.Column('semester_id', sa.String(length=255), nullable=True),
    sa.Column('learning_summary', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_collection_name'), 'chat_sessions', ['collection_name'], unique=False)
    op.create_index(op.f('ix_chat_sessions_faculty_id'), 'chat_sessions', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_semester_id'), 'chat_sessions', ['semester_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_semester_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_faculty_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_collection_name'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
